apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-module-controller-manager
  namespace: og
  labels:
    app.kubernetes.io/name: test-module-controller-manager
    app.kubernetes.io/version: 0.0.10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-module-controller-manager
  template:
    metadata:
      labels:
        app: test-module-controller-manager
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
        - name: test-module-controller-manager
          image: ealen/echo-server
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 100m
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: 'test-module-telemetry'
  labels: 
    app.kubernetes.io/version: 0.0.10
  annotations: {}
  namespace: og
spec: {}
