apiVersion: operator.kyma-project.io/v1beta2
kind: ModuleTemplate
metadata:
  annotations:
    source: https://raw.githubusercontent.com/OliwiaGowor/testing/refs/heads/main/test-module-template.yaml
    new-ann: test
    test: test
  labels:
    operator.kyma-project.io/module-name: test-module
  name: test-module-0.0.10
  namespace: og
spec:
  associatedResources:
    - group: operator.kyma-project.io
      kind: Telemetry
      version: v1alpha1
  data:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: Telemetry
    metadata:
      name: test-module-telemetry
      namespace: og
    spec:
      nodeSpreadLabel: topology.kubernetes.io/zone
  descriptor: {}
  info:
    documentation: https://github.com/pbochynski
    icons:
      - link: https://raw.githubusercontent.com/pbochynski/cluster-ip/refs/heads/main/logo.png
        name: module-icon
    repository: https://github.com/OliwiaGowor/testing
  manager:
    group: apps
    kind: Deployment
    name: test-module-controller-manager
    namespace: og
    version: v1
  mandatory: false
  moduleName: test-module
  requiresDowntime: false
  resources:
    - link: https://raw.githubusercontent.com/OliwiaGowor/testing/refs/heads/main/test-module.yaml
      name: rawManifest
  version: 0.0.10
